- clean: ['~']


- link:
    # Vim Configuration
    ~/.vimrc.after: vim/.vimrc.after
    ~/.vimrc.keys: vim/.vimrc.keys
    ~/.vimrc: vim/.vimrc

    # Vim Custom Configuration
    # ~/.vimrc.local: vim/.vimrc.local
    ~/.vimrc.keys.local: vim/.vimrc.keys.local

    # TMUX Configuration
    ~/.tmux.conf: tmux/.tmux.conf

    # Zsh Configuration
    ~/.zshrc: oh-my-zsh/.zshrc

    # Zsh Custom Configuration
    ~/.zshrc.local: oh-my-zsh/.zshrc.local

    # Oh My Zsh Themes
    ~/.oh-my-zsh/themes/mildronize.zsh-theme: oh-my-zsh/themes/mildronize.zsh-theme

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    # - [tmux source-file ~/.tmux.conf, Reloading TMUX configuration (Run in TMUX only)]
