#!/usr/bin/env bash

# Install Vim Plug
VIMPLUGPATH="~/.vim/autoload/plug.vim"
if [ ! -f "$VIMPLUGPATH" ]; then
    curl -fLo $VIMPLUGPATH --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo "Vim Plug is already installed!"
fi
