#!/usr/bin/env bash

# http://stackoverflow.com/a/677212
hash git 2>/dev/null || { echo >&2 "git isn't installed.  Aborting."; exit 1; }
hash curl 2>/dev/null || { echo >&2 "curl isn't installed.  Aborting."; exit 1; }
hash zsh 2>/dev/null || { echo >&2 "zsh isn't installed.  Aborting."; exit 1; }
hash tmux 2>/dev/null || { echo >&2 "tmux isn't installed.  Aborting."; exit 1; }
hash vim 2>/dev/null || { echo >&2 "vim isn't installed.  Aborting."; exit 1; }

TARGET_PATH="$HOME/.dotfiles"
VIMPLUG_PATH="$HOME/.vim/autoload/plug.vim"

# Install Vim Plug
if [ ! -f "$VIMPLUG_PATH" ]; then
    curl -fLo $VIMPLUG_PATH --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo "Vim Plug is already installed!"
fi

# Run dotbot
$TARGET_PATH/dotbot && \
    vim +PlugInstall +qall && \
    zsh



