#!/usr/bin/env zsh

# http://stackoverflow.com/a/677212
hash git 2>/dev/null || { echo >&2 "git isn't installed.  Aborting."; exit 1; }
hash curl 2>/dev/null || { echo >&2 "curl isn't installed.  Aborting."; exit 1; }
hash zsh 2>/dev/null || { echo >&2 "zsh isn't installed.  Aborting."; exit 1; }
hash tmux 2>/dev/null || { echo >&2 "tmux isn't installed.  Aborting."; exit 1; }
hash vim 2>/dev/null || { echo >&2 "vim isn't installed.  Aborting."; exit 1; }

TARGET_PATH="$HOME/.dotfiles"
VIMPLUG_PATH="$HOME/.vim/autoload/plug.vim"
TPM_PATH="$HOME/.tmux/plugins/tpm"

if [ ! -d "$TARGET_PATH" ]; then
    echo "~/.dotfiles isn't existing. Please run ~/.dotfiles/install"
    exit 1
fi

if [ ! -f "$VIMPLUG_PATH" ]; then
    echo "Vim Plug isn't installed . Please run ~/.dotfiles/install"
    exit 1
fi


# Install Tmux Plugin
if [ ! -d "$TPM_PATH" ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
    echo "Tmux Plugin Manager is already installed!"
fi

{ echo "Creating... symbol link with dotbot"; $TARGET_PATH/dotbot; } && \
    { echo "Installing vim plugin"; vim +PlugInstall +qall; } && \
    echo "All done!"

