#!/usr/bin/env bash

# Fix not same color inside tmux of xfce4-terminal http://unix.stackexchange.com/questions/139082/zsh-set-term-screen-256color-in-tmux-but-xterm-256color-without-tmux
# This site explain why must fix with this way
echo "export TERM=xterm-256color" >> ~/.bashrc

